### ISSUE TITLE
Installation of mos-tool under Ubuntu/Debian with amd64 architecture fails

### ISSUE THREAD

**Issue by mamuesp** [cesanta/mos-tool#12]
When trying to install mos via the process described on the web site - under Ubuntu or Debian with amd64 architecture - the call of `sudo apt-get mos` throws an error and fails - it seems that there are packages for the amd64 architecture missing:
```bash
W: The repository 'http://ppa.launchpad.net/mongoose-os/mos/ubuntu cosmic Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/mongoose-os/mos/ubuntu/dists/cosmic/main/binary-amd64/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
```
and the attempt to install leads to (understandable):
```bash
E: Unable to locate package mos
```
Downloading directly with `curl`or `wget` works fine instead.

**Comment by rojer** [comment]
currently packages are provided for ubuntu 16.04 (xenial xerus), 17.10 (artful aadvark) and 18.04 (bionic beaver).

**Comment by mamuesp** [comment]
Ok, this must have been some version mismatch in the installation ... after upgrading from "Xenial Xerus" to "Bionic Beaver" the installation works absolutely fine. :smile:

**Comment by rojer** [comment]
fwiw, added cosmic packages build in https://github.com/cesanta/mos-tool/commit/bd20881a9e4a15a492fa4f53c3f1319f722bf933
