### ISSUE TITLE
`mos` crashing on startup (Linux)

### ISSUE THREAD

**Issue by r8d8** [cesanta/mos-tool#2]
`mos` crashes periodicaly on startup ([trace.txt](https://github.com/cesanta/mos-tool/files/1703033/trace.txt)). 
Port 1992 is clean, and  no other instances launched. 
OS: ArchLinux
```bash
$ sudo nmap -sTU -O 127.0.0.1

Starting Nmap 7.60 ( https://nmap.org ) at 2018-02-07 14:13 EET
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00016s latency).
Not shown: 1997 closed ports
PORT     STATE         SERVICE
3306/tcp open          mysql
5432/tcp open          postgresql
68/udp   open|filtered dhcpc
Device type: general purpose
Running: Linux 3.X|4.X
OS CPE: cpe:/o:linux:linux_kernel:3 cpe:/o:linux:linux_kernel:4
OS details: Linux 3.8 - 4.9
Network Distance: 0 hops

OS detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 2.96 seconds
```

**Comment by cpq** [comment]
To clarify, mos crashes when scanned by nmap, or just crashes even if nothing talks to it?

**Comment by r8d8** [comment]
@cpq, even if nothing touches it.

**Comment by cpq** [comment]
@dimonomid please take a look at this!

**Comment by dimonomid** [comment]
@r8d8 , trying to figure where the problem is; could you please run `mos` with `GODEBUG` env var set to `netdns=cgo` and see if it still fails? Like this:
```
$ GODEBUG=netdns=cgo+1 mos flash esp8266
```
(the `cgo` part is to force C resolver, and `+1` part is needed to print debug information)

**Comment by dimonomid** [comment]
Also, I guess the best bet for you would be to build mos tool from source: https://github.com/cesanta/mos-tool (see instructions there, they are for Ubuntu, but I think you'll figure how to tailor them for arch :) )

The right thing for us is to build proper arch packages of course, but no ETA for that at the moment.

**Comment by r8d8** [comment]
@dimonomid, tried with env var, looks like same ([trace.txt](https://github.com/cesanta/mos-tool/files/1707277/trace.txt))
Will try to build it, and then let you know about results. Thanks.

**Comment by r8d8** [comment]
Yeap, building from sources solved issue.

**Comment by dimonomid** [comment]
Great, thanks for testing it and getting back to us.

Yeah, we should really provide AUR package.
