### ISSUE TITLE
can't save device config in expert view

### ISSUE THREAD

**Issue by bricewge** [cesanta/mos-tool#21]
When using the expert view to modify the configuration of a device I can't save it. The logs says `Incoming frame is too big, dropping.` so I think that when saving (in expert view only) all the config is sent to the device instead of just the diff between the config on the device and the new on.

Someone else is getting this issue: https://forum.mongoose-os.com/discussion/3303/esp32-expert-view-problem-incoming-frame-is-too-big-dropping-mongoose

**Comment by bricewge** [comment]
Since `2.7` has a new UI without this view, this issue isn't relevant anymore.

**Comment by rojer** [comment]
we plan to add config editor to new mos, so stay tuned.
