### ISSUE TITLE
cloning private libs with SSH agent is broken on linux

### ISSUE THREAD

**Issue by bricewge** [cesanta/mos-tool#22]
Clonging private libs when using a SSH agent is broken on linux since bc73437230943959a297d32db35d5f9a6c939b5a.
```
ads1015-i2c: Does not exist, cloning from "gitea@git.sama.re:proxiwash/ads1015-i2c.git"...
Error: exit status 128
/home/bricewge/misc/go/src/cesanta.com/common/go/ourgit/ourgit_shell.go:204: cloning gitea@git.sama.re:proxiwash/ads1015-i2c.git: Cloning into '/home/bricewge/.mos/apps-2.5.1/esclave-ip/deps/ads1015-i2c'...
gitea@git.sama.re: Permission denied (publickey).
fatal: Could not read from remote repository.
```
This is because the shell's git is used by default and that the environment is modified with `GIT_TERMINAL_PROMPT=0` [here](https://github.com/cesanta/mos-tool/blob/master/common/go/ourgit/ourgit_shell.go#L187-L199). When this is set I don't get a prompt from `pinentry` to unlock my smartcard and even if the smartcard has been unlocked just before.

Current workaround is to use `--use-go-git=true` (not present in the help BTW), here `pinentry` is correctly called and the repo is cloned.

**Comment by rojer** [comment]
it seems that the workaround is no longer necessary, i'm sending a change to remove it.

thanks for reporting!
