### ISSUE TITLE
MOS 2.8 Linux - RPC over AWS IoT MQTT transport not working

### ISSUE THREAD

**Issue by kurtroberts** [cesanta/mos-tool#24]
Using a command that works on the mac results in a context deadline exceeded error on Linux.  I first encountered the error while trying to move the project into a docker container, but i get the same result on my hardware linux box.

The device has rpc_mqtt loaded as part of it's firmware, and it advertises an RPC method that lets it blink.  The script was a little more complex, but I've boiled it down to this test case.

```
$ cat blink.sh
#!/bin/bash

device=$1
mqttPort=${2-"mqtts://[redacted]:8883"}

mos --cert-file aws-${device}.crt.pem --key-file aws-${device}.key.pem --port $mqttPort/${device} call Blink

```
On the mac:
```
$ blink.sh [PEM KEY NAME HERE]
"blinky blinky..."
```
On Linux:
```
$ blink.sh [PEM KEY NAME HERE]
Error: context deadline exceeded
/Users/mos/tmp/mos_gopath/src/cesanta.com/common/go/mgrpc/mgrpc.go:434: 
/Users/mos/tmp/mos_gopath/src/cesanta.com/mos/dev/dev_conn.go:222: 
/Users/mos/tmp/mos_gopath/src/cesanta.com/mos/main.go:171: call failed 
```
Mac and Linux laptops are on the same wifi, are pulling keys from a shared secrets store.  I get the same behavior on the real linux box as I do in the docker container.

I tried building an older release on linux to see if I could further isolate it, but there's something wrong with my go environment.

**Comment by rojer** [comment]
how old is the firmware you are talking to? could be [this](https://github.com/cesanta/mos-tool/commit/cfe9ab27233a40dbbea466215189ddc7c2f1d91e) change.

**Comment by rojer** [comment]
actually, no, that's a different issue. i reproduced it and working on a fix.

**Comment by rojer** [comment]
cut 2.8.1 with the fix
