### ISSUE TITLE
Feature Request - mos flash --keep-fs

### ISSUE THREAD

**Issue by DrBomb** [cesanta/mos-tool#27]
When flashing a device, all files inside it get erased by the new fs partition. For us that are with deployed devices in the field it means that stuff like jstores that are created in runtime are lost forever.

How about a flag that requests a full FS copy before flashing, then restores said backup after flashing?

Yes, I understand that OTA does this. But on cellular connected devices OTA is awful, and RPC OTA takes at least half an hour over serial. Serial flashes are very fast, only that keeping the FS would be the best to have.

**Comment by mamuesp** [comment]
This is already possible. Read in the HowTos about adding a FS with content. It's explained in detail. And if you create an additional FS, this stays untouched when flashing as well.
Only thing is - there should be a way to automate that. I started some excercises in GO - perhaps I find the time to complete these ideas.

**Comment by DrBomb** [comment]
Your answer is not helpful nor it is pertinent to the request.

**Comment by mamuesp** [comment]
I believe we aren't compatible in communication - just tried to help. Will stay silent the next time, sorry!
