### ISSUE TITLE
`mos` crashes on firmware upload (Linux)

### ISSUE THREAD

**Issue by r8d8** [cesanta/mos-tool#3]
`mos` crashes during firmware upload with a next error in log window:
```bash
Loaded https://mongoose-os.com/downloads/api.json
Server Error: connection errStror
```
OS: Archlinux 
Related to #2 
![2018-02-07-163055_1600x900_scrot](https://user-images.githubusercontent.com/8018746/35921855-91941fb4-0c24-11e8-804c-d3b6bf8e7d64.png)

**Comment by Mebus** [comment]
hm. same problem on Fedora.

Mebus
