### ISSUE TITLE
cannot load older version of mos tool

### ISSUE THREAD

**Issue by fovea1959** [cesanta/mos-tool#32]
Trying to staple my mos tool down to version 2.8.0 for regression testing.  Still end up with the latest version.

```
$ mos update 2.8.0
Update channel: release
Running sudo apt-get update
Running apt-cache showpkg mos
Running sudo apt-get install -y mos
Reading package lists... Done
Building dependency tree       
Reading state information... Done
mos is already the newest version (2.10.2+67fae67~bionic0).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
```

**Comment by cpq** [comment]
I believe this is due to the fact that `mos` tool has been installed via `apt`.
I am sure that the curl-based installation would work as expected.

@rojer could you comment on the apt-based installation please?

**Comment by fovea1959** [comment]
cpq is correct, as documented in
[https://forum.mongoose-os.com/discussion/comment/6266/#Comment_6266](
https://forum.mongoose-os.com/discussion/comment/6266/#Comment_6266)

May want to update documentation?

**Comment by nliviu** [comment]
There is a recent commit which will force the use of PPA on Ubuntu: https://github.com/cesanta/mos-tool/commit/f990e84e1c7adc3ffd0d5b5972ddd696992cbbe2

**Comment by rojer** [comment]
so, we actually do keep older debs around now but support for installing them is not yet integrated into the tool.

**Comment by fjp** [comment]
I have the same issue on macOS. Cannot update to an older version.

```
$ mos update 2.7.0
Update channel: release
Running brew update
Running brew tap cesanta/mos
Running brew install mos
Warning: cesanta/mos/mos 2.12.1 is already installed and up-to-date
To reinstall 2.12.1, run `brew reinstall mos`
```

**Comment by nliviu** [comment]
@fjp https://forum.mongoose-os.com/discussion/comment/7998/#Comment_7998

**Comment by fjp** [comment]
Thanks @nliviu it works.
