### ISSUE TITLE
Unable to encrypt flash on ESP32

### ISSUE THREAD

**Issue by gadget-man** [cesanta/mos-tool#37]
I'm unable to properly enable encryption on a production ESP32 WRover board. According to @rojer the issue is linked to coding_scheme, which is set to 1 on the WRover, but 0 on any dev boards I've tried.

Attached the following dumps:
[Dev Board Working.txt](https://github.com/cesanta/mos-tool/files/2922503/Dev.Board.Working.txt)
[Prod Board before encryption.txt](https://github.com/cesanta/mos-tool/files/2922504/Prod.Board.before.encryption.txt)
[Prod Board after encryption.txt](https://github.com/cesanta/mos-tool/files/2922505/Prod.Board.after.encryption.txt)

**Comment by rojer** [comment]
this has been released in mos-latest 201903041227
