### ISSUE TITLE
Increase the context deadline

### ISSUE THREAD

**Issue by DrBomb** [cesanta/mos-tool#5]
We need a way to increase the timeout for RPC calls. In situations with low bandwidth such as remote locations on cellular. The RPC commands are eventually received by the controller, but the mos tool times out.

**Comment by rojer** [comment]
[--timeout](https://github.com/cesanta/mos-tool/blob/89bbddb0191e4118db8ae915008fe36db56c5c6c/mos/dev/client.go#L20)?

**Comment by rojer** [comment]
ok, i realized that this is not the whole story - config and filesystem ops use different constants.
i'll fix this.

**Comment by DrBomb** [comment]
awesome, thank you rojer
